[models]
  [models.llm]
    [models.llm."chatglm-6b"]
    type = "chatglm"
    path = "THUDM/chatglm-6b"
    [models.llm."chatglm-6b-int8"]
    type = "chatglm"
    path = "THUDM/chatglm-6b-int8"
    [models.llm."chatglm-6b-int4"]
    type = "chatglm"
    path = "THUDM/chatglm-6b-int4"
    [models.llm."chatglm2-6b"]
    type = "chatglm"
    path = "THUDM/chatglm2-6b"
    [models.llm."chatglm2-6b-int8"]
    type = "chatglm"
    path = "THUDM/chatglm2-6b-int8"
    [models.llm."chatglm2-6b-int4"]
    type = "chatglm"
    path = "THUDM/chatglm2-6b-int4"
    [models.llm."phoenix-inst-chat-7b"]
    type = "phoenix"
    path = "FreedomIntelligence/phoenix-inst-chat-7b"
    [models.llm."phoenix-inst-chat-7b-int4"]
    type = "phoenix"
    path = "FreedomIntelligence/phoenix-inst-chat-7b-int4"

  [models.embeddings]
    [models.embeddings."text2vec-large-chinese"]
    type = "default"
    path = "GanymedeNil/text2vec-large-chinese"

[auth]
tokens = ["2Uux8o0uaAoQt3RJnTB6Oe7KiVf_6DQesxnnEjc1u8kdBQKmt"]

[tunnel]
  [tunnel.ngrok]
  token = "2Uux8o0uaAoQt3RJnTB6Oe7KiVf_6DQesxnnEjc1u8kdBQKmt"
  region = "jp"
  # Binding custom subdomains is a feature for paid accounts.
  subdomain = ""
  [tunnel.cloudflare]
  # first need init cloudflare tunnel, see README.md
  cloudflared_path = "/usr/local/bin/cloudflared"
  # tunnel name, see README.md
  name = "chatglm-openai-api"